name = "caliber-corporate"
compatibility_date = "2025-11-30"
compatibility_flags = ["nodejs_compat"]
main = "worker.ts"

[[kv_namespaces]]
binding = "KV"
id = "0356f2290c784e4789b76a9c1956bdda"

[[d1_databases]]
binding = "DB"
database_name = "caliber-db"
database_id = "55a19e36-ed5b-4a31-83db-56ec83dd9a71"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[assets]
directory = "dist/client"
